//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuXuat
    {
        public string phieuXuat_id { get; set; }
        public string product_id { get; set; }
        public Nullable<int> quanlity { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PhieuXuat PhieuXuat { get; set; }
    }
}
