//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.PhieuXuats = new HashSet<PhieuXuat>();
        }
    
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string cmnd { get; set; }
        public string avatar { get; set; }
        public Nullable<int> countProducts { get; set; }
        public Nullable<decimal> totalMoney { get; set; }
        public string username { get; set; }
        public string Address { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<PhieuXuat> PhieuXuats { get; set; }
    }
}
