//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail
    {
        public int id { get; set; }
        public string product_id { get; set; }
        public string CPU { get; set; }
        public string SoNhan { get; set; }
        public string SoLuong { get; set; }
        public string Speed { get; set; }
        public string MaxSpeed { get; set; }
        public string Cache { get; set; }
        public string RAM { get; set; }
        public string RAM_type { get; set; }
        public string BusRAM { get; set; }
        public string MaxRAM { get; set; }
        public string OCung { get; set; }
        public string ManHinh { get; set; }
        public string DoPhanGiai { get; set; }
        public string TanSoQuet { get; set; }
        public string CongNgheManHinh { get; set; }
        public string VGA { get; set; }
        public string AmThanh { get; set; }
        public string CongGiaoTiep { get; set; }
        public string KetNoiKhongDay { get; set; }
        public string Webcam { get; set; }
        public string TinhNangKhac { get; set; }
        public string DenBanPhim { get; set; }
        public string SizeAndWeight { get; set; }
        public string ChatLieu { get; set; }
        public string Pin { get; set; }
        public string HeDieuHanh { get; set; }
        public string RaMat { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
