//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ChiTietPhieuNhaps = new HashSet<ChiTietPhieuNhap>();
            this.Details = new HashSet<Detail>();
            this.Images = new HashSet<Image>();
            this.promotions = new HashSet<promotion>();
            this.ChiTietPhieuXuats = new HashSet<ChiTietPhieuXuat>();
        }
    
        public string id { get; set; }
        public string Name { get; set; }
        public Nullable<int> quanlity { get; set; }
        public Nullable<int> purchase { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> trademark_id { get; set; }
        public string avatar { get; set; }
        public Nullable<int> view_ { get; set; }
    
        public virtual ICollection<ChiTietPhieuNhap> ChiTietPhieuNhaps { get; set; }
        public virtual Description Description { get; set; }
        public virtual ICollection<Detail> Details { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual Trademark Trademark { get; set; }
        public virtual ICollection<promotion> promotions { get; set; }
        public virtual PromotionsGift PromotionsGift { get; set; }
        public virtual ICollection<ChiTietPhieuXuat> ChiTietPhieuXuats { get; set; }
    }
}
