//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public string product_id { get; set; }
        public System.DateTime date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<decimal> price_after { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
