//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromotionsGift
    {
        public string product_id { get; set; }
        public string gift1 { get; set; }
        public string gift2 { get; set; }
        public string gift3 { get; set; }
        public string gift4 { get; set; }
        public Nullable<decimal> priceSum { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
