//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMenu
    {
        public tblMenu()
        {
            this.tblPhanQuyens = new HashSet<tblPhanQuyen>();
        }
    
        public string MaMenu { get; set; }
        public string TenMenu { get; set; }
        public string ParentMenu { get; set; }
    
        public virtual ICollection<tblPhanQuyen> tblPhanQuyens { get; set; }
    }
}
