//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAnAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhanQuyen
    {
        public string MaNhomNguoiDung { get; set; }
        public string MaMenu { get; set; }
        public Nullable<bool> CoQuyen { get; set; }
        public Nullable<System.DateTime> setTime { get; set; }
    
        public virtual tblMenu tblMenu { get; set; }
        public virtual tblNhomNguoiDung tblNhomNguoiDung { get; set; }
    }
}
